apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netdocuments-integration.fullname" . }}-appsettings
data:
  appsettings.json: |
    {
      "ConsoleApiKey": {{ .Values.consoleApiKey | quote }},
      "NetDocs": {
        {{- with .Values.netDocuments }}
        "OAuthTokenUrl": {{ .oAuthTokenUrl | quote }},
        "ApiUrl": {{ .apiUrl | quote }},
        "ClientId": {{ .clientId | quote }},
        "ClientSecret": {{ .clientSecret | quote }},

        "RepositoryId": {{ .repositoryId | quote }},
        "CabinetId": {{ .cabinetId | quote }},
        "ClientAttributeId": {{ .clientAttributeId | quote }},
        "MatterAttributeId": {{ .matterAttributeId | quote }}
        {{- end }}
      },
      "Prime": {
        {{- with .Values.evolvePrime }}
        "ApiUrl": {{ .apiUrl | quote }},
        "TokenEndpoint": {{ .tokenEndpoint | quote }},
        "Scope": {{ .scope | quote }},
        "ClientId": {{ .clientId | quote }},
        "ClientSecret": {{ .clientSecret | quote }},
        "SigningKey": {{ .signingKey | quote }},
        "ReceiverUrl": {{ .receiverUrl | quote }},

        "Tenant": {{ .tenant | quote }},
        "ApiKey": {{ .apiKey | quote }}
        {{- end }}
      }
    }